try {
  null.myFunction();
} catch(e) {  
  console.log(e);
} finally {
  console.log('Programm continue');
}

